lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import rating_statistics.urls
import users.urls

urlpatterns = [
    path("", include(homepage.urls)),
    path("about/", include(about.urls)),
    path("catalog/", include(catalog.urls)),
    path("download/", include(download.urls)),
    path("feedback/", include(feedback.urls)),
    path("statistics/", include(rating_statistics.urls)),
    path("admin/", admin.site.urls),
    path("users/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

lyceum/users/urls.py
from django.contrib.auth import views as v
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        v.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        v.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        v.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        v.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        v.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        v.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        v.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        v.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "users/",
        views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "users/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
]

lyceum/users/models.py
from sys import argv

from django.contrib.auth.models import BaseUserManager, User
from django.db import models
from sorl.thumbnail import get_thumbnail

__all__ = []


class Profile(models.Model):
    def get_path(self, filename):
        return f"users/{self.user_id}/{filename}"

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    birthday = models.DateField(
        "дата рождения",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        "аватарка",
        upload_to=get_path,
        blank=True,
    )
    coffee_count = models.PositiveIntegerField(
        "количество переходов по /coffee/",
        default=0,
    )

    def get_image_300x300(self):
        return get_thumbnail(self.image, "300x300", crop="center", quality=51)

    class Meta:
        verbose_name = "Дополнительное поле"
        verbose_name = "Дополнительные поля"


class UserManager(BaseUserManager):
    def active(self):
        return (
            self.get_queryset()
            .filter(
                is_active=True,
            )
            .select_related(
                User.profile.related.name,
            )
        )

    def by_mail(self, email):
        return self.active().get(
            email=email,
        )


class User(User):
    objects = UserManager()

    class Meta:
        proxy = True


if "makemigrations" not in argv and "migrate" not in argv:
    User._meta.get_field("email")._unique = True

lyceum/users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import Profile, User

__all__ = []


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            User.username.field.name,
            "password1",
            "password2",
        )


class UserForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            User.email.field.name,
            User.first_name.field.name,
            User.last_name.field.name,
        )


class ProfileForm(forms.ModelForm):
    coffee_count = forms.IntegerField(
        label="Количество переходов по /coffee/",
        disabled=True,
    )

    class Meta:
        model = Profile
        fields = (
            Profile.birthday.field.name,
            Profile.image.field.name,
            Profile.coffee_count.field.name,
        )

lyceum/users/views.py
from datetime import timedelta
from http import HTTPStatus

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic, View

from users.forms import ProfileForm, SignupForm, UserForm
from users.models import Profile, User


__all__ = []


class SignupView(generic.FormView):
    model = User
    form_class = SignupForm
    template_name = "users/signup.html"
    success_url = reverse_lazy("users:signup")

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        new_user = form.save(commit=False)
        new_user.set_password(form.cleaned_data["password1"])
        new_user.is_active = settings.DEFAULT_USER_IS_ACTIVE
        new_user.save()
        send_mail(
            "Subject",
            "Для активации пользователя перейдите на эту страницу:\n"
            f"http://127.0.0.1:8000/auth/activate/{username}/",
            settings.MAIL,
            [username],
            fail_silently=False,
        )

        messages.success(self.request, "Форма успешно отправлена!")
        return super().form_valid(form)


class ActivateView(View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, username=kwargs.get("username"))
        enddate = user.date_joined + timedelta(hours=12)

        if timezone.now() > enddate:
            return HttpResponse(status=HTTPStatus.METHOD_NOT_ALLOWED)

        user.is_active = True
        user.save()

        return render(request, "users/activate_done.html", {})


class UserListView(generic.ListView):
    template_name = "users/user_list.html"
    context_object_name = "users"
    queryset = (
        User.objects.filter(
            is_active=True,
        )
        .order_by(
            User.username.field.name,
        )
        .only(
            User.username.field.name,
        )
    )


class UserDetailView(generic.DetailView):
    template_name = "users/user_detail.html"
    context_object_name = "user"
    queryset = (
        User.objects.filter(
            is_active=True,
        )
        .select_related(
            User.profile.related.name,
        )
        .only(
            User.email.field.name,
            User.first_name.field.name,
            User.last_name.field.name,
            f"{User.profile.related.name}__{Profile.birthday.field.name}",
            f"{User.profile.related.name}__{Profile.image.field.name}",
            f"{User.profile.related.name}__{Profile.coffee_count.field.name}",
        )
    )


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = "users/profile.html"

    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=request.user.id)
        user_form = UserForm(request.POST or None, instance=user)
        try:
            profile_form = ProfileForm(
                request.POST or None,
                request.FILES or None,
                instance=user.profile,
            )
        except Exception:
            profile_form = ProfileForm(
                request.POST,
                request.FILES,
            )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Данные успешно сохранены!")
            return redirect("users:profile")

        return self.render_to_response(
            {
                "user_form": user_form,
                "profile_form": profile_form,
            },
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(pk=self.request.user.id)
        user_form = UserForm(self.request.POST or None, instance=user)
        try:
            profile_form = ProfileForm(
                self.request.POST or None,
                instance=user.profile,
            )
        except Exception:
            profile_form = ProfileForm(self.request.POST or None)
        context["user_form"] = user_form
        context["profile_form"] = profile_form
        return context

lyceum/templates/users/activate_done.html
{% extends 'base.html' %}
{% block title %}
  Пользователь активирован
{% endblock %}
{% block content %}
  <h1>Пользователь активирован</h1>
{% endblock %}

lyceum/templates/users/login.html
{% extends 'base.html' %}
{% block title %}
  Логин
{% endblock %}
{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <h1>Логин</h1>
  {% include 'includes/form.html' %}
{% endblock %}

lyceum/templates/users/logout.html
{% extends 'base.html' %}
{% block title %}
  Не авторизован
{% endblock %}
{% block content %}
  <h1>Не авторизован</h1>
  <p>Благодарим вас за время, проведенное на этом сайте.</p>
  <a href="{% url 'users:login' %}">Войти снова</a>
{% endblock %}

lyceum/templates/users/password_change.html
{% extends 'base.html' %}
{% block title %}
Изменение пароля
{% endblock %}
{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <h1>Изменение пароля</h1>
  <p>В целях безопасности, пожалуйста, введите свой старый пароль, затем введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.</p>
  {% include 'includes/form.html' %}
{% endblock %}

lyceum/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}
  Пароль успешно изменен
{% endblock %}
{% block content %}
  <h1>Пароль успешно изменен</h1>
  <p>Ваш пароль был изменен.</p>
{% endblock %}

lyceum/templates/users/password_reset.html
{% extends 'base.html' %}
{% block title %}
  Восстановление пароля
{% endblock %}
{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <h1>Восстановление пароля</h1>
  <p>Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем вам инструкцию, как установить новый пароль.</p>
  {% include 'includes/form.html' %}
{% endblock %}

lyceum/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}
  Восстановление пароля завершено
{% endblock %}
{% block content %}
  <h1>Восстановление пароля завершено</h1>
  <p>Ваш пароль был сохранен. Теперь вы можете войти.</p>
  <a href="{% url 'users:login' %}">Войти снова</a>
{% endblock %}

lyceum/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
  Введите новый пароль
{% endblock %}
{% block content %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <h1>Введите новый пароль</h1>
  <p>Пожалуйста, введите новый пароль дважды, чтобы мы могли убедиться в правильности написания.</p>
  {% include 'includes/form.html' %}
{% endblock %}

lyceum/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}
  Письмо с инструкциями по восстановлению пароля отправлено
{% endblock %}
{% block content %}
  <h1>Письмо с инструкциями по восстановлению пароля отправлено</h1>
  <p>Мы отправили вам инструкцию по установке нового пароля на указанный адрес электронной почты (если в нашей базе данных есть такой адрес). Вы должны получить ее в ближайшее время.</p>
  <p>Если вы не получили письмо, пожалуйста, убедитесь, что вы ввели адрес с которым Вы зарегистрировались, и проверьте папку со спамом.</p>
{% endblock %}

lyceum/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}
  Мой профиль
{% endblock %}
{% block content %}
  {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
    </div>
  {% endfor %}
  <h1 class="text-center" style="margin-bottom: 50px;">Мой профиль</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in user_form %}
      <div class="mb-3">
        <label class="form-label">{{ field.label_tag }}</label>
        {{ field }}
        {% if field.help_text %}
          <div class="form-text">{{ field.help_text|safe }}</div>
        {% endif %}
      </div>
    {% endfor %}
    {% for field in profile_form %}
      <div class="mb-3">
        <label class="form-label">{{ field.label_tag }}</label>
        {{ field }}
        {% if field.help_text %}
          <div class="form-text">{{ field.help_text|safe }}</div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <form action="{% url 'homepage:coffee' %}">
      <button type="submit" class="btn btn-primary">выпить кофе</button>
    </form>
  </form>
{% endblock %}

lyceum/templates/users/signup.html
{% extends 'base.html' %}
{% block title %}
  Регистрация
{% endblock %}
{% block content %}
  {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
    </div>
  {% endfor %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        {{ error|escape }}
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      {{ error|escape }}
    {% endfor %}
  {% endif %}
  <h1 class="text-center" style="margin-bottom: 50px;">Регистрация</h1>
  {% include 'includes/form.html' %}
{% endblock %}

lyceum/templates/users/user_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ user.first_name }}
{% endblock %}
{% block content %}
  {% if user.image %}
    <img src="{{ user.get_image_300x300.url }}">
  {% endif %}
  <h1 class="text-center">Имя: {% if user.first_name %}{{ user.first_name }}{% else %}неуказано{% endif %}</h1>
  <h1 class="text-center">Фамилия: {% if user.last_name %}{{ user.last_name }}{% else %}неуказано{% endif %}</h1>
  <h2 class="text-center">Почта: {{ user.email }}</h2>
  <h3 class="text-center">День рождения: {{ user.profile.birthday }}</h3>
  <h3 class="text-center">Сколько раз человек попытался выпить кофе: {{ user.profile.coffee_count }}</h3>
{% endblock %}

lyceum/templates/users/user_list.html
{% extends 'base.html' %} {% block title %}
  Список пользователей
{% endblock %} {% block content %}
  <h1 class="text-center" style="margin-bottom: 50px">Список пользователей</h1>
  <div class="container text-center">
    {% for user in users %}
      <h3><a href="{% url 'users:user_detail' user.id %}">{{ user.username }}</a></h3>
      {% empty %}
      <p>Список пуст. Эй, админ добавь инфы!</p>
    {% endfor %}
  </div>
{% endblock %}