lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

lyceum/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"

urlpatterns = [
    path("", views.ItemListView.as_view(), name="item_list"),
    path("<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"),
    path("new/", views.ItemNewView.as_view(), name="new"),
    path("friday/", views.ItemFridayView.as_view(), name="friday"),
    path("unverified/", views.ItemUnverifiedView.as_view(), name="unverified"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import rating_statistics.urls
import users.urls

urlpatterns = [
    path("", include(homepage.urls)),
    path("about/", include(about.urls)),
    path("catalog/", include(catalog.urls)),
    path("download/", include(download.urls)),
    path("feedback/", include(feedback.urls)),
    path("statistics/", include(rating_statistics.urls)),
    path("admin/", admin.site.urls),
    path("users/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

lyceum/rating_statistics/urls.py
import django.urls

import rating_statistics.views

app_name = "statistics"

urlpatterns = [
    django.urls.path(
        "by_users/",
        rating_statistics.views.RatingByUsers.as_view(),
        name="by_users",
    ),
    django.urls.path(
        "by_items/",
        rating_statistics.views.RatingByItems.as_view(),
        name="by_items",
    ),
    django.urls.path(
        "by_one_user/",
        rating_statistics.views.RatingByCurrentUser.as_view(),
        name="by_one_user",
    ),
]

lyceum/users/urls.py
from django.contrib.auth import views as v
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        v.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        v.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        v.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        v.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        v.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        v.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        v.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        v.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "users/",
        views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "users/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
]

lyceum/rating/models.py
from django.core.exceptions import ValidationError
from django.db import models

from catalog.models import Item
from rating.managers import RatingManager
from users.models import User


__all__ = []


STATUS_CHOICES = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
]
# STATUS_CHOICES_DICT = {
#     "Ненависть": 1,
#     "Неприязнь": 2,
#     "Нейтрально": 3,
#     "Обожание": 4,
#     "Любовь": 5,
# }


class Rating(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="пользователь",
        related_name="ratings",
    )
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        verbose_name="товар",
        related_name="ratings",
    )
    rating = models.IntegerField(
        "оценка",
        choices=STATUS_CHOICES,
        default=3,
    )

    objects = RatingManager()

    class Meta:
        verbose_name = "оценка"
        verbose_name_plural = "оценки"
        default_related_name = "ratings"

    def __str__(self):
        return self.rating

    def save(self, *args, **kwargs):
        if (
            type(self)
            .objects.filter(
                user_id=self.user.id,
                item_id=self.item.id,
            )
            .exclude(id=self.id)
            .count()
            > 0
        ):
            raise ValidationError(
                "Один пользователь может поставить только одну оценку товару",
            )
        super().save(*args, **kwargs)

lyceum/rating_statistics/views.py
import django.contrib.auth.decorators
import django.utils.decorators
import django.views.generic

import catalog.models
import rating.models

__all__ = []


class RatingByUsers(django.views.generic.ListView):
    def get_queryset(self):
        return rating.models.Rating.objects.by_users()

    template_name = "rating_statistics/by_users.html"
    item_context_name = "users"
    http_method_names = ["get", "head"]


class RatingByItems(django.views.generic.ListView):
    def get_queryset(self):
        return rating.models.Rating.objects.by_items()

    template_name = "rating_statistics/by_items.html"
    item_context_name = "items"
    http_method_names = ["get", "head"]


@django.utils.decorators.method_decorator(
    django.contrib.auth.decorators.login_required,
    name="dispatch",
)
class RatingByCurrentUser(django.views.generic.ListView):
    template_name = "rating_statistics/by_one_user.html"
    item_context_name = "ratings"
    http_method_names = ["get", "head"]

    def get_queryset(self):
        return (
            rating.models.Rating.objects.filter(
                user=self.request.user,
            )
            .select_related(rating.models.Rating.item.field.name)
            .values(
                "__".join(
                    [
                        rating.models.Rating.item.field.name,
                        catalog.models.Item.id.field.name,
                    ],
                ),
                "__".join(
                    [
                        rating.models.Rating.item.field.name,
                        catalog.models.Item.name.field.name,
                    ],
                ),
                rating.models.Rating.rating.field.name,
            )
        ).order_by(f"-{rating.models.Rating.rating.field.name}")

lyceum/templates/rating_statistics/by_items.html
{% extends 'base.html' %}
{% block title %}
  Статистика по товарам
{% endblock %}
{% block content %}
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>Cтатистика по товарам</h1>
  </div>
  {% for item, values in object_list.items %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Последняя максимальная оценка</th>
        <th scope="col">Последняя минимальная оценка</th>
        <th scope="col">Количество оценок</th>
        <th scope="col">Средняя оценка товара</th>
      </tr>
    </thead>
    <tbody>
          <tr>
          <th><a href="{% url "catalog:item_detail" item.id %}">{{ item.name }}</a></th>
          <td>{{ values.max.rating }} — <a href="{% url "users:user_detail" pk=user.id %}">автор</a></td>
          <td>{{ values.min.rating }} — <a href="{% url "users:user_detail" pk=user.id %}">автор</a></td>
          <td>{{ values.amount }}</td>
          <td>{{ values.average|floatformat:2 }}</td>
          </tr>
    </tbody>
  </table>
  {% endfor %}
</div>
{% endblock %}

lyceum/templates/rating_statistics/by_one_user.html
{% extends 'base.html' %}
{% block title %}
  Ваши отзывы
{% endblock %}
{% block content %}
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>Ваши отзывы</h1>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Товар</th>
        <th scope="col">Оценка</th>
      </tr>
    </thead>
    <tbody>
      {% for rating in rating_list %}
        <tr>
          <th scope="row"><a href="{% url "catalog:item_detail" rating.item__id %}">{{ rating.item__name }}</a></th>
          <td>{{ rating.rating }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

lyceum/templates/rating_statistics/by_users.html
{% extends 'base.html' %}
{% block title %}
  Статистика по пользователям
{% endblock %}
{% block content %}
<div class="container">
  <div class="d-flex justify-content-center">
    <h1>Статистика по пользователям</h1>
  </div>
{% for user, values in object_list.items %}
{% if values.amount != 0 %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Имя пользователя</th>
        <th scope="col">Лучший товар</th>
        <th scope="col">Худший товар</th>
        <th scope="col">Кол-во оценок</th>
        <th scope="col">Средняя оценка пользователя</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th><a href="{% url "users:user_detail" pk=user.id %}">{{ user }}</a></th>
        <td><a href="{% url "catalog:item_detail" values.max.item %}">Товар</a> — оценка: {{ values.max.rating }}</td>
        <td><a href="{% url "catalog:item_detail" values.min.item %}">Товар</a> — оценка: {{ values.min.rating }}</td>
        <td>{{ values.amount }}</td>
        <td>{{ values.average|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
{% else %}
  <h2>Нет данных</h2>
{% endif %}
{% endfor %}
</div>
{% endblock %}