lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

lyceum/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"

urlpatterns = [
    path("", views.ItemListView.as_view(), name="item_list"),
    path("<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"),
    path("new/", views.ItemNewView.as_view(), name="new"),
    path("friday/", views.ItemFridayView.as_view(), name="friday"),
    path("unverified/", views.ItemUnverifiedView.as_view(), name="unverified"),
]

lyceum/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("coffee/", views.CoffeeView.as_view(), name="coffee"),
    path("echo/", views.EchoView.as_view(), name="echo"),
    path("echo/submit/", views.EchoSubmitView.as_view(), name="echo_submit"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import rating_statistics.urls
import users.urls

urlpatterns = [
    path("", include(homepage.urls)),
    path("about/", include(about.urls)),
    path("catalog/", include(catalog.urls)),
    path("download/", include(download.urls)),
    path("feedback/", include(feedback.urls)),
    path("statistics/", include(rating_statistics.urls)),
    path("admin/", admin.site.urls),
    path("users/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

lyceum/templates/includes/birthdays.html
{% load static %}
<div>
  {% for user in birthday_users %}
    <div id="{{user.pk}}">
      <p>
        Сегодня празднует {{ user.username }} с почтой {{ user.email|default:"<i>неуказано</i>" }}
      </p>
    </div>
    <script>
      var birthday = new Date(Date.parse('{{ user.profile.birthday|date:"Y-m-d" }}'));
      var now = new Date(Date.now());
      if (!(birthday.getMonth() === now.getMonth() && birthday.getDate() === now.getDate())){
        $("#{{user.pk}}").css("display", "none");
      };
    </script>
  {% endfor %}
</div>

lyceum/templates/includes/footer.html
<footer>
  <h1 class="text-center" style="padding-top: 40px;">2023 "Лучшая компания на свете"</h1>
</footer>

lyceum/templates/includes/form.html
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <div class="mb-3">
      <label for="{{ field.id_for_label }}" class="form-label">
        {{ field.label_tag }}
        {% if field.field.required %}
          <span>*</span>
        {% endif %}
      </label>
      {{ field }}
      {% if field.help_text %}
        <div id="{{ field.id_for_label }}-help" class="form-text">{{ field.help_text|safe }}</div>
      {% endif %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-primary">Отправить</button>
</form>

lyceum/templates/includes/header.html
{% load static %}
<header>
  <div class="container text-center" style="padding: 10px;">
    <div class="row">
      <a class="navbar-brand" href="{% url 'homepage:home' %}"><img src="{% static 'img/logo.png' %}" class="rounded d-block col-2" /></a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-underline justify-content-center col fs-4">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'homepage:home' %}active{% endif %}" href="{% url 'homepage:home' %}">На главную</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'about:about' %}active{% endif %}" href="{% url 'about:about' %}">О проекте</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'catalog:item_list' %}active{% endif %}" href="{% url 'catalog:item_list' %}">Список товаров</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'feedback:feedback' %}active{% endif %}" href="{% url 'feedback:feedback' %}">Оставить отзыв</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Вход</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:profile' %}active{% endif %}" href="{% url 'users:profile' %}">Профиль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выход</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'statistics:by_users' %}active{% endif %}" href="{% url 'statistics:by_users' %}">Статистика по пользователям</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'statistics:by_items' %}active{% endif %}" href="{% url 'statistics:by_items' %}">Статистика по товарам</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'statistics:by_one_user' %}active{% endif %}" href="{% url 'statistics:by_one_user' %}">Ваша статистика</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:user_list' %}active{% endif %}" href="{% url 'users:user_list' %}">Все пользователи</a>
          </li>
          {% if request.user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link text-secondary" href="{% url 'admin:index' %}">Админ</a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </div>
</header>

lyceum/templates/includes/item_card.html
<div class="rounded bg-light" style="padding-bottom: 30px">
  <h3 class="text-center"><a href="{% url 'catalog:item_detail' item.id %}">{{ item.name }}</a></h3>
  <h4 class="text-center">{{ item.category.name }}</h4>
  <p class="text-center">{{ item.text|safe|truncatewords_html:10 }}</p>
  <div class="container text-center">
    <div class="row row-cols-2">
      {% for tag in item.tags.all %}
        <div class="col rounded bg-secondary text-white" style="margin-bottom: 10px">
          <span>{{ tag.name }}</span>
        </div>
        {% empty %}
        <p>Список пуст. Эй, админ добавь инфы!</p>
      {% endfor %}
    </div>
  </div>
</div>