lyceum/about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.AboutView.as_view(), name="about"),
]

lyceum/catalog/urls.py
from django.urls import path

from catalog import views


app_name = "catalog"

urlpatterns = [
    path("", views.ItemListView.as_view(), name="item_list"),
    path("<int:pk>/", views.ItemDetailView.as_view(), name="item_detail"),
    path("new/", views.ItemNewView.as_view(), name="new"),
    path("friday/", views.ItemFridayView.as_view(), name="friday"),
    path("unverified/", views.ItemUnverifiedView.as_view(), name="unverified"),
]

lyceum/download/urls.py
from django.urls import path

from download import views

app_name = "download"

urlpatterns = [
    path("<path:path>", views.file, name="file"),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

import about.urls
import catalog.urls
import download.urls
import feedback.urls
import homepage.urls
import rating_statistics.urls
import users.urls

urlpatterns = [
    path("", include(homepage.urls)),
    path("about/", include(about.urls)),
    path("catalog/", include(catalog.urls)),
    path("download/", include(download.urls)),
    path("feedback/", include(feedback.urls)),
    path("statistics/", include(rating_statistics.urls)),
    path("admin/", admin.site.urls),
    path("users/", include(users.urls)),
    path("auth/", include(django.contrib.auth.urls)),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
        )
    urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

lyceum/users/urls.py
from django.contrib.auth import views as v
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        v.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        v.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        v.PasswordChangeView.as_view(
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        v.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        v.PasswordResetView.as_view(
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        v.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        v.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        v.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "signup/",
        views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "users/",
        views.UserListView.as_view(),
        name="user_list",
    ),
    path(
        "users/<int:pk>/",
        views.UserDetailView.as_view(),
        name="user_detail",
    ),
    path(
        "profile/",
        views.ProfileView.as_view(),
        name="profile",
    ),
]

lyceum/catalog/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.safestring import mark_safe
from django_ckeditor_5.fields import CKEditor5Field

from catalog.validators import WordsValidator
from core.models import Base, ImageBase

__all__ = []


class Category(Base):
    slug = models.SlugField(
        "слаг",
        max_length=200,
        help_text="Максимум 200 символов",
        unique=True,
    )

    weight = models.PositiveSmallIntegerField(
        "вес",
        validators=[
            MinValueValidator(
                1,
                message="Значение должно быть больше 0",
            ),
            MaxValueValidator(
                32767,
                message="Значение должно быть меньше 32767",
            ),
        ],
        default=100,
        help_text="Max 32767",
    )

    class Meta:
        ordering = ("name", "id")
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name


class Tag(Base):
    slug = models.SlugField(
        "слаг",
        max_length=200,
        help_text="Максимум 200 символов",
        unique=True,
    )

    class Meta:
        ordering = ("slug", "id")
        verbose_name = "тег"
        verbose_name_plural = "теги"
        default_related_name = "tags"

    def __str__(self):
        return self.name


class ItemManager(models.Manager):
    def on_main(self):
        return (
            self.published()
            .filter(
                is_on_main=True,
            )
            .order_by(
                Item.name.field.name,
            )
        )

    def published(self):
        return (
            self.get_queryset()
            .filter(
                is_published=True,
                category__is_published=True,
            )
            .order_by(
                f"{Item.category.field.name}__{Category.name.field.name}",
                Item.name.field.name,
            )
            .select_related(
                Item.category.field.name,
                Item.main_image.related.name,
            )
            .prefetch_related(
                models.Prefetch(
                    Item.tags.field.name,
                    queryset=Tag.objects.filter(is_published=True).only(
                        Tag.name.field.name,
                    ),
                ),
            )
            .only(
                Item.name.field.name,
                Item.text.field.name,
                Item.main_image.related.name,
                f"{Item.category.field.name}__{Category.name.field.name}",
                f"{Item.tags.field.name}__{Tag.name.field.name}",
            )
        )


class Item(Base):
    objects = ItemManager()

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="категория",
        help_text="Выберите категорию",
    )
    is_on_main = models.BooleanField(
        "на главной",
        default=False,
    )
    tags = models.ManyToManyField(Tag)
    text = CKEditor5Field(
        "текст",
        validators=[
            WordsValidator(
                "превосходно",
                "роскошно",
            ),
        ],
        help_text=(
            "Описание должно содержать слова 'превосходно' или 'роскошно'"
        ),
    )
    updated = models.DateTimeField(
        "время изменения",
        auto_now=True,
        null=True,
        blank=True,
    )
    created = models.DateTimeField(
        "время создания",
        auto_now_add=True,
        null=True,
        blank=True,
    )

    class Meta:
        ordering = ("name", "id")
        verbose_name = "товар"
        verbose_name_plural = "товары"
        default_related_name = "items"

    def __str__(self):
        return self.text[:15]

    def image_tmb(self):
        if self.main_image.image:
            return mark_safe(
                f"<img src='{self.main_image.get_image_50x50.url}'>",
            )
        return "Нет изображения"

    image_tmb.short_description = "превью"
    image_tmb.allow_tags = True


class MainImage(ImageBase):
    item = models.OneToOneField(
        Item,
        on_delete=models.CASCADE,
        related_name="main_image",
    )

    def __str__(self):
        return self.item.name

    class Meta:
        verbose_name = "главное изображение"
        verbose_name_plural = "главные изображения"


class Image(ImageBase):
    item = models.ForeignKey(
        Item,
        on_delete=models.CASCADE,
        related_name="images",
    )

    class Meta:
        verbose_name = "фото"
        verbose_name_plural = "фото"

lyceum/catalog/views.py
import datetime
from random import sample

from django.contrib import messages
from django.db import models
from django.shortcuts import redirect
from django.views import generic

from catalog.models import Image, Item
from rating.forms import RatingForm
from rating.models import Rating

__all__ = []

ITEMS_PER_PAGE = 5


class ItemNewView(generic.DetailView):
    template_name = "catalog/special.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items_ids = list(
            Item.objects.published()
            .filter(
                created__gte=datetime.date.today()
                - datetime.timedelta(days=7),
            )
            .values_list("id", flat=True),
        )

        try:
            selected = sample(items_ids, ITEMS_PER_PAGE)
        except ValueError:
            selected = items_ids

        context["items"] = Item.objects.published().filter(pk__in=selected)
        context["title"] = "Новинки"
        return context


class ItemFridayView(generic.DetailView):
    template_name = "catalog/special.html"
    context_object_name = "items"
    queryset = (
        Item.objects.published()
        .filter(updated__week_day=6)
        .order_by(
            f"-{Item.updated.field.name}",
        )[:5]
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Пятница"
        return context


class ItemUnverifiedView(generic.DetailView):
    template_name = "catalog/special.html"
    context_object_name = "items"
    queryset = (
        Item.objects.published()
        .filter(
            created__gte=models.F(
                Item.updated.field.name,
            )
            - datetime.timedelta(seconds=1),
            created__lte=models.F(
                Item.updated.field.name,
            )
            + datetime.timedelta(seconds=1),
        )
        .order_by(
            "?",
        )[:5]
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Непроверенное"
        return context


class ItemListView(generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = Item.objects.published()


class ItemDetailView(generic.DetailView):
    template_name = "catalog/item_detail.html"
    context_object_name = "item"
    queryset = Item.objects.published().prefetch_related(
        models.Prefetch(
            Item.images.field.related_query_name(),
            queryset=Image.objects.only(
                Image.image.field.name,
                Image.item_id.field.name,
            ),
        ),
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item_id = kwargs.get("object").id

        if self.request.user.is_authenticated:
            try:
                current_user_rating = Rating.objects.get(
                    user_id=self.request.user.id,
                    item_id=item_id,
                )
                rating_form = RatingForm(instance=current_user_rating)
            except Rating.DoesNotExist:
                rating_form = RatingForm()
            context["rating_form"] = rating_form

        context["ratings"] = Rating.objects.filter(item_id=item_id)
        context["ratings_count"] = len(context["ratings"])
        context["average_rating"] = (
            sum(
                map(lambda x: x.rating or 0, context["ratings"]),
            )
            / context["ratings_count"]
            if context["ratings_count"] != 0
            else 0
        )
        return context

    def post(self, request, *args, **kwargs):
        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            try:
                rating = Rating.objects.get(
                    user=request.user,
                    item_id=kwargs.get("pk"),
                )
            except Rating.DoesNotExist:
                rating = Rating(
                    user=request.user,
                    item_id=kwargs.get("pk"),
                )
            rating.rating = rating_form.cleaned_data.get("rating")
            rating.save()
            messages.success(request, "Данные успешно сохранены!")
        return redirect("catalog:item_detail", kwargs.get("pk"))

lyceum/templates/catalog/item_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ item.name }}
{% endblock %}
{% block content %}
  {% for message in messages %}
    <div class="container-fluid p-0">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">{{ message }}</div>
    </div>
  {% endfor %}
  <h1 class="text-center">{{ item.name }}</h1>
  {% if item.main_image.image %}
    <div class="text-center">
      <img src="{{ item.main_image.get_image_300x300.url }}" />
      <a href="{% url 'download:file' item.main_image.image %}" class="btn btn-lg btn-primary">Скачать изображение</a>
    </div>
  {% endif %}
  <h5 class="text-center">{{ item.text|safe }}</h5>
  <h3 class="text-center">{{ item.category.name }}</h3>
  <div class="container text-center">
    {% for tag in item.tags.all %}
      <div class="rounded bg-secondary text-white" style="margin-bottom: 10px;">
        <span>{{ tag.name }}</span>
      </div>
      {% empty %}
      <p>Список пуст. Эй, админ добавь инфы!</p>
    {% endfor %}
  </div>
  <div class="text-center">
    {% for image in item.images.all %}
      <div style="margin-bottom: 15px;">
        <img src="{{ image.get_image_300x300.url }}" />
      </div>
      <p>
        <a href="{% url 'download:file' image.image %}" class="btn btn-lg btn-primary">Скачать изображение</a>
      </p>
      {% empty %}
      <p>Список пуст. Эй, админ добавь инфы!</p>
    {% endfor %}
  </div>
  {% if request.user.is_authenticated %}
    <div class="text-center">
      <form method="post">
        {% csrf_token %}
        {% for field in rating_form %}
          <div class="mb-3">
            <label class="form-label">{{ field.label_tag }}</label>
            {{ field }}
            {% if field.help_text %}
              <div class="form-text">{{ field.help_text|safe }}</div>
            {% endif %}
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить оценку</button>
      </form>
    </div>
  {% endif %}
  {% if ratings %}
    <h3 class="text-center">Оценки</h3>
    <h4 class="text-center">Количество оценок: {{ ratings_count }}</h4>
    <h4 class="text-center">Средняя оценка: {{ average_rating }}</h4>
    {% for rating in ratings %}
      <div class="text-center">
        <a href="{% url 'users:user_detail' rating.user.id %}">{{ rating.user.username }}</a>
        <a> — {{ rating.rating }}</a>
      </div>
      {% empty %}
      <p>Список пуст. Эй, админ добавь инфы!</p>
    {% endfor %}
  {% endif %}
{% endblock %}

lyceum/templates/catalog/item_list.html
{% extends 'base.html' %} {% block title %}
  Список товаров
{% endblock %} {% block content %}
  <h1 class="text-center" style="margin-bottom: 50px">Список товаров</h1>
  <div class="container text-center">
    {% for item in items %}
      {% ifchanged item.category.name %}
      <h2>{{ item.category.name }}</h2>
      {% endifchanged %}
      <div class="rounded bg-light" style="margin-bottom: 30px">
        <h3 class="text-center"><a href="{% url 'catalog:item_detail' item.id %}">{{ item.name }}</a></h3>
        <p class="text-center">{{ item.text|safe|truncatewords_html:10 }}</p>
        <div class="container text-center">
          <div class="row row-cols-2">
            {% for tag in item.tags.all %}
              <div class="col rounded bg-secondary text-white" style="margin-bottom: 10px">
                <span>{{ tag.name }}</span>
              </div>
              {% empty %}
              <p>Список пуст. Эй, админ добавь инфы!</p>
            {% endfor %}
          </div>
        </div>
      </div>
      {% empty %}
      <p>Список пуст. Эй, админ добавь инфы!</p>
    {% endfor %}
  </div>
{% endblock %}

lyceum/templates/catalog/special.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <h1 class="text-center" style="margin-bottom: 50px;">{{ title }}</h1>
  <div class="container text-center">
    <div class="row row-cols-3">
      {% for item in items %}
        <div class="col" style="margin-bottom: 10px;">
          {% include 'includes/item_card.html' %}
        </div>
        {% empty %}
        <p>Список пуст. Эй, админ добавь инфы!</p>
      {% endfor %}
    </div>
  </div>
{% endblock %}